name: Release

on:
  push:
    tags:
      - 1.*
      - 2.*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 1.8
          distribution: zulu
      - name: Build with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B deploy --file pom.xml --settings ci/settings.xml